name: Build and deploy Node.js app to Azure Web App - hungryfoxes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Upload source code for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-source
          path: |
            .  # Upload entire source code
            !node_modules  # Exclude node_modules
            !.next  # Exclude the build directory

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-source

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hungryfoxes'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98F45D864FC742F3B332DB3C68769426 }}
