# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hungryfoxes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build || (echo "Build failed!" && exit 1)
      - name: List files (debug)
        run: ls -la .next

      #- name: Zip artifact for deployment
      #  run: zip next.zip ./* .next -qr
      - name: Zip artifact for deployment
        run: zip -r next.zip .next public package.json package-lock.json next.config.mjs
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: next.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          
      - name: Unzip artifact for deployment
        #run: unzip next.zip -d output
        run: unzip next.zip -d /home/chaman/wwwroot

      - name: List downloaded files (debug)
        run: ls -la /home/chaman/wwwroot
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_595A8B05B2CF431EBC0C11F8C21AFD40 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A1BE32B1E4AA454A96C1A6B9B160A830 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CB91B1D0D26842FCA840558CDD66C57F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hungryfoxes'
          slot-name: 'Production'
          package: output
          
