name: Deploy Node.js app to Azure Web App - hungryfoxes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hungryfoxes'
          slot-name: 'Production'
          package: . # Deploys only the source code, Azure will build it
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98F45D864FC742F3B332DB3C68769426 }}
